runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
beta_settings:
  'source_reference': 'https://github.com/P3rdigas/IPM_Project.git#7ac03d017a0ad8ca6826e5bbea1049017a13f6e4'
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /.*
  script: unused
  login: optional
  secure: optional
